version: "3"

services:
  webserver:
    build: ./bin/webserver
    container_name: 'cesar-archive'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      - MYSQL_HOST=png-mysql
      - MYSQL_CESAR_DATABASE=sample_database
      - MYSQL_CESAR_USER=root
      - MYSQL_CESAR_PASSWORD=tiger
      - ARCHIVE_ENDPOINT=http://cesar.esa.int/sun_monitor/archive/
  mysql:
    build: ./bin/mysql
    container_name: 'cesar-archive-db'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./sample_database.sql:/home/sample_database.sql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: sample_database
      MYSQL_USER: cesar
      MYSQL_PASSWORD: archive
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'cesar-archive-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
